/**
 * Codex app-server protocol types, and the narrow envelope shapes we read off
 * the wire.
 *
 * The types are **referenced in place** from `resources/codex-protocol/` rather
 * than copied into `src/`. That directory is generated by
 * `codex app-server generate-ts` and is the source of truth (HANDOFF fact 5);
 * copying it here would mean 642 files to re-sync by hand every time Codex
 * moves. Every import below is `import type`, so nothing survives compilation
 * and the `resources/` tree never enters the bundle or the test runtime.
 * `tsconfig.json` excludes `resources/` from its include globs, but exclude
 * only filters those globs -- files pulled in by an import are still part of
 * the program, which is why this typechecks.
 *
 * This module re-exports only what the adapter actually uses, so the rest of
 * the adapter has one place to look and one place to fix if Codex renames
 * something.
 */

export type { RequestId } from "../../../../resources/codex-protocol/RequestId";
export type { ServerNotification } from "../../../../resources/codex-protocol/ServerNotification";
export type { ServerRequest } from "../../../../resources/codex-protocol/ServerRequest";
export type { ClientInfo } from "../../../../resources/codex-protocol/ClientInfo";
export type { MessagePhase } from "../../../../resources/codex-protocol/MessagePhase";
export type { WebSearchItem } from "../../../../resources/codex-protocol/WebSearchItem";
export type { ThreadItem } from "../../../../resources/codex-protocol/v2/ThreadItem";
export type { UserInput } from "../../../../resources/codex-protocol/v2/UserInput";
export type { Thread } from "../../../../resources/codex-protocol/v2/Thread";
export type { Turn } from "../../../../resources/codex-protocol/v2/Turn";
export type { TurnError } from "../../../../resources/codex-protocol/v2/TurnError";
export type { ThreadStatus } from "../../../../resources/codex-protocol/v2/ThreadStatus";
export type { ThreadTokenUsage } from "../../../../resources/codex-protocol/v2/ThreadTokenUsage";
export type { TokenUsageBreakdown } from "../../../../resources/codex-protocol/v2/TokenUsageBreakdown";
export type { FileUpdateChange } from "../../../../resources/codex-protocol/v2/FileUpdateChange";
export type { Model as CodexModel } from "../../../../resources/codex-protocol/v2/Model";
export type { ThreadStartParams } from "../../../../resources/codex-protocol/v2/ThreadStartParams";
export type { SandboxMode } from "../../../../resources/codex-protocol/v2/SandboxMode";
export type { ThreadStartResponse } from "../../../../resources/codex-protocol/v2/ThreadStartResponse";
export type { ThreadResumeParams } from "../../../../resources/codex-protocol/v2/ThreadResumeParams";
export type { ThreadForkParams } from "../../../../resources/codex-protocol/v2/ThreadForkParams";
export type { ThreadForkResponse } from "../../../../resources/codex-protocol/v2/ThreadForkResponse";
export type { ThreadReadParams } from "../../../../resources/codex-protocol/v2/ThreadReadParams";
export type { ThreadReadResponse } from "../../../../resources/codex-protocol/v2/ThreadReadResponse";
export type { TurnStartParams } from "../../../../resources/codex-protocol/v2/TurnStartParams";
export type { TurnStartResponse } from "../../../../resources/codex-protocol/v2/TurnStartResponse";
export type { TurnInterruptParams } from "../../../../resources/codex-protocol/v2/TurnInterruptParams";
export type { ModelListParams } from "../../../../resources/codex-protocol/v2/ModelListParams";
export type { ModelListResponse } from "../../../../resources/codex-protocol/v2/ModelListResponse";
export type { InitializeParams } from "../../../../resources/codex-protocol/InitializeParams";
export type { InitializeResponse } from "../../../../resources/codex-protocol/InitializeResponse";
export type { JsonValue } from "../../../../resources/codex-protocol/serde_json/JsonValue";

import type { RequestId } from "../../../../resources/codex-protocol/RequestId";
import type { ServerNotification } from "../../../../resources/codex-protocol/ServerNotification";
import type { ServerRequest } from "../../../../resources/codex-protocol/ServerRequest";
import type { CommandExecutionRequestApprovalResponse } from "../../../../resources/codex-protocol/v2/CommandExecutionRequestApprovalResponse";
import type { FileChangeRequestApprovalResponse } from "../../../../resources/codex-protocol/v2/FileChangeRequestApprovalResponse";
import type { McpServerElicitationRequestResponse } from "../../../../resources/codex-protocol/v2/McpServerElicitationRequestResponse";
import type { ThreadItem } from "../../../../resources/codex-protocol/v2/ThreadItem";

/** Narrow a `ThreadItem` to one variant, e.g. `CodexItem<"commandExecution">`. */
export type CodexItem<K extends ThreadItem["type"]> = Extract<ThreadItem, { type: K }>;

// ---------------------------------------------------------------------------
// Wire envelopes
// ---------------------------------------------------------------------------

/**
 * app-server speaks JSON-RPC-shaped messages over stdio, one per LF-terminated
 * line. Four envelopes arrive from the server, distinguished by which of
 * `id` / `method` / `result` / `error` are present:
 *
 * - `{id, result}` / `{id, error}` -- a response to a request we sent
 * - `{id, method, params}` -- a `ServerRequest`; the turn BLOCKS until answered
 * - `{method, params}` -- a notification
 */
export type CodexResponse =
	| { id: RequestId; result: unknown; error?: never }
	| { id: RequestId; result?: never; error: { code: number; message: string; data?: unknown } };

/** Generated discriminated unions; aliases keep adapter imports local. */
export type CodexServerRequest = ServerRequest;
export type CodexNotification = ServerNotification;

export type CodexServerMessage = CodexResponse | CodexServerRequest | CodexNotification;

export function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function isCodexResponse(msg: CodexServerMessage): msg is CodexResponse {
	return "id" in msg && !("method" in msg);
}

export function isCodexServerRequest(msg: CodexServerMessage): msg is CodexServerRequest {
	return "id" in msg && "method" in msg;
}

export function isCodexNotification(msg: CodexServerMessage): msg is CodexNotification {
	return !("id" in msg) && "method" in msg;
}

/** A typed lookup key for one app-server's wire namespace (`0` !== `"0"`). */
export function wireRequestKey(id: RequestId): string {
	return JSON.stringify([typeof id, id]);
}

/**
 * Server requests that block a turn and whose decline shape we know, so
 * `reply(id, null)` can decline rather than erroring the request out.
 * Sourced from `ServerRequest.ts` + the matching `*Response` types.
 */
export const DECLINE_RESPONSES: Readonly<Record<string, unknown>> = {
	"item/commandExecution/requestApproval": {
		decision: "decline",
	} satisfies CommandExecutionRequestApprovalResponse,
	"item/fileChange/requestApproval": {
		decision: "decline",
	} satisfies FileChangeRequestApprovalResponse,
	"mcpServer/elicitation/request": {
		action: "decline",
		content: null,
		_meta: null,
	} satisfies McpServerElicitationRequestResponse,
};
